name: Auto Tag Release

on:
  push:
    branches:
      - main
    paths:
      - "version.go"
      - "go.mod"
      - "go.sum"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Get package version
        id: get_version
        run: |
          VERSION=$(grep 'const Version = ' version.go | cut -d'"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          if git tag -l "${{ steps.get_version.outputs.version }}" | grep -q "${{ steps.get_version.outputs.version }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.check_tag.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "${{ steps.get_version.outputs.version }}" -m "Release ${{ steps.get_version.outputs.version }}"
          git push origin "${{ steps.get_version.outputs.version }}"

          # Create a GitHub release
          gh release create "${{ steps.get_version.outputs.version }}" \
            --title "${{ steps.get_version.outputs.version }}" \
            --notes "Release ${{ steps.get_version.outputs.version }}" \
            --draft=false \
            --prerelease=false
