name: Version Check

on:
  push:
    branches-ignore: [main, master]
  pull_request:
    branches: [main, master]
    types: [opened, ready_for_review]

jobs:
  check-version:
    name: Checking Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get base version
        id: base_version
        run: |
          set -x # Enable debugging
          git fetch origin ${{ github.base_ref }}

          # Check if file exists on base branch
          if ! git cat-file -e origin/${{ github.base_ref }}:version.go; then
            echo "version.go does not exist on base branch origin/${{ github.base_ref }}"
            BASE_VERSION="v0.0.0"
          else
            echo "Attempting to get version from origin/${{ github.base_ref }}:version.go"
            GIT_SHOW_OUTPUT=$(git show origin/${{ github.base_ref }}:version.go 2>/dev/null)
            echo "Raw output from git show:"
            echo "$GIT_SHOW_OUTPUT"
            
            BASE_VERSION=$(echo "$GIT_SHOW_OUTPUT" | grep 'const Version = ' | cut -d'"' -f2 || echo "")
          fi

          if [ -z "$BASE_VERSION" ]; then
            echo "Could not extract version string from base branch file. Assuming initial version."
            BASE_VERSION="v0.0.0"
          fi
          set +x # Disable debugging
          echo "Final Base Version: $BASE_VERSION"
          echo "base_version=$BASE_VERSION" >> $GITHUB_OUTPUT

      - name: Get PR version
        id: pr_version
        run: |
          set -x # Enable debugging
          if [ ! -f version.go ]; then
             echo "version.go not found in PR branch checkout"
             exit 1
          fi
          PR_VERSION=$(grep 'const Version = ' version.go | cut -d'"' -f2)
          if [ -z "$PR_VERSION" ]; then
            echo "Could not find version string in PR branch version.go"
            exit 1
          fi
          set +x # Disable debugging
          echo "Final PR Version: $PR_VERSION"
          echo "pr_version=$PR_VERSION" >> $GITHUB_OUTPUT

      - name: Check version update
        run: |
          # Function to compare semantic versions
          version_compare() {
            # Remove 'v' prefix if present
            local a=${1#v}
            local b=${2#v}
            
            # Split into major.minor.patch
            local a1 a2 a3 b1 b2 b3
            IFS='.' read -r a1 a2 a3 <<< "$a"
            IFS='.' read -r b1 b2 b3 <<< "$b"
            
            # Compare major versions
            if [ "$a1" -gt "$b1" ]; then return 0; fi
            if [ "$a1" -lt "$b1" ]; then return 1; fi
            
            # Compare minor versions
            if [ "$a2" -gt "$b2" ]; then return 0; fi
            if [ "$a2" -lt "$b2" ]; then return 1; fi
            
            # Compare patch versions
            if [ "$a3" -gt "$b3" ]; then return 0; fi
            if [ "$a3" -lt "$b3" ]; then return 1; fi
            
            return 1
          }

          BASE_VERSION="${{ steps.base_version.outputs.base_version }}"
          PR_VERSION="${{ steps.pr_version.outputs.pr_version }}"

          echo "Comparing Base: $BASE_VERSION with PR: $PR_VERSION"

          if [ "$BASE_VERSION" = "$PR_VERSION" ]; then
            echo "Version must be updated in version.go before creating a PR"
            echo "Current version: $BASE_VERSION"
            exit 1
          fi

          if ! version_compare "$PR_VERSION" "$BASE_VERSION"; then
            echo "Version must be incremented in version.go"
            echo "Base version: $BASE_VERSION"
            echo "PR version: $PR_VERSION"
            echo "The PR version must be higher than the base version"
            exit 1
          fi

          echo "Version check passed!"
